DISCORD_BOT_TOKEN: ''
DISCORD_CLIENT_ID: ''
DISCORD_CLIENT_SECRET: ''
DISCORD_SERVER_ID: ''
DISCORD_ANNOUNCEMENT_CHANNEL_ID: ''
HOST: ''
GMAIL_USERNAME: ''
GMAIL_PASSWORD: ''
AZURE_CLIENT_ID: ''
AZURE_CLIENT_SECRET: ''
